# Generated by Django 5.2.3 on 2025-06-19 07:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='subject',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_subject',
            field=models.CharField(choices=[('BCT001', 'Software Engineering'), ('BCT002', 'System Analysis and Design'), ('BCT003', 'Operating System'), ('BCT004', 'Object Oriented Programming'), ('BCT005', 'Electornics & Instrumentation')], default='N/A', max_length=20, verbose_name='Assignment Subject'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='question_file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/questions/', verbose_name='Select Assignment File'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher', verbose_name='Uploaded By'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, choices=[('BCA', 'Bachelor of Computer Application'), ('BCT', 'Bachelor of Computer Engineering'), ('BEI', 'Bachelor of Electronics and Information'), ('BCE', 'Bachelor of Civil Engineering')], default='N/A', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='join_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Join Date'),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Material Title')),
                ('category', models.CharField(choices=[('SLIDE', 'Chapter Slide'), ('TEXT_BOOK', 'A text book'), ('REFERENCE_BOOK', 'A reference book'), ('OLD_QUESTION', 'Previous board exam question'), ('AUDIO_BOOK', 'An audio book')], max_length=30, verbose_name='Category')),
                ('description', models.CharField(default='', max_length=255, verbose_name='Material Description')),
                ('material_subject', models.CharField(choices=[('BCT001', 'Software Engineering'), ('BCT002', 'System Analysis and Design'), ('BCT003', 'Operating System'), ('BCT004', 'Object Oriented Programming'), ('BCT005', 'Electornics & Instrumentation')], default='N/A', max_length=20, verbose_name='Material Subject')),
                ('material_file', models.FileField(upload_to='material/', verbose_name='Select file')),
                ('upload_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Upload Date')),
                ('teacher', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.teacher')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materials',
                'ordering': ['-title'],
            },
        ),
        migrations.DeleteModel(
            name='Materials',
        ),
    ]
